//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Game.Config.StarForce
{
    public sealed partial class Armor : BeanBase
    {
        public Armor(JSONNode _buf)
        {
            {
                if (!_buf["Id"].IsNumber)
                {
                    throw new SerializationException();
                }

                Id = _buf["Id"];
            }
            {
                if (!_buf["MaxHP"].IsNumber)
                {
                    throw new SerializationException();
                }

                MaxHP = _buf["MaxHP"];
            }
            {
                if (!_buf["Defense"].IsNumber)
                {
                    throw new SerializationException();
                }

                Defense = _buf["Defense"];
            }
            PostInit();
        }

        public static Armor DeserializeArmor(JSONNode _buf)
        {
            return new Armor(_buf);
        }

        /// <summary>
        /// 装甲编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 最大生命
        /// </summary>
        public readonly int MaxHP;

        /// <summary>
        /// 防御力
        /// </summary>
        public readonly int Defense;

        public const int __ID__ = 1299209866;

        public override int GetTypeId()
        {
            return __ID__;
        }

        public void ResolveRef(Tables tables)
        {
        }

        public override string ToString()
        {
            return "{ "
                   + "Id:" + Id + ","
                   + "MaxHP:" + MaxHP + ","
                   + "Defense:" + Defense + ","
                   + "}";
        }

        partial void PostInit();
    }
}