//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;
using Luban;
using SimpleJSON;

namespace Game.Config.StarForce
{
    public partial class TbArmor : IDataTable
    {
        private readonly Dictionary<int, Armor>  _dataMap;
        private readonly List<Armor>             _dataList;
        private readonly Func<UniTask<JSONNode>> _loadFunc;

        public TbArmor(Func<UniTask<JSONNode>> loadFunc)
        {
            _loadFunc = loadFunc;
            _dataMap = new Dictionary<int, Armor>();
            _dataList = new List<Armor>();
        }

        public async UniTask LoadAsync()
        {
            var _json = await _loadFunc();
            _dataMap.Clear();
            _dataList.Clear();
            foreach (var _ele in _json.Children)
            {
                Armor _v;
                {
                    if (!_ele.IsObject)
                    {
                        throw new SerializationException();
                    }

                    _v = Armor.DeserializeArmor(_ele);
                }
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, Armor> DataMap => _dataMap;
        public List<Armor> DataList => _dataList;

        public Armor GetOrDefault(int key)
        {
            return _dataMap.TryGetValue(key, out var v) ? v : null;
        }

        public Armor Get(int key)
        {
            return _dataMap[key];
        }

        public Armor this[int key] => _dataMap[key];

        public void ResolveRef(Tables tables)
        {
            foreach (var _v in _dataList)
            {
                _v.ResolveRef(tables);
            }
        }


        partial void PostInit();
    }
}