
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class L10N : Luban.BeanBase
{
    public L10N(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["en"].IsString) { throw new SerializationException(); }  En = _buf["en"]; }
        { if(!_buf["zh_CN"].IsString) { throw new SerializationException(); }  ZhCN = _buf["zh_CN"]; }
        { if(!_buf["zh_TW"].IsString) { throw new SerializationException(); }  ZhTW = _buf["zh_TW"]; }
    }

    public static L10N DeserializeL10N(JSONNode _buf)
    {
        return new L10N(_buf);
    }

    /// <summary>
    /// 文本key
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string En;
    /// <summary>
    /// 简体中文
    /// </summary>
    public readonly string ZhCN;
    /// <summary>
    /// 繁体中文
    /// </summary>
    public readonly string ZhTW;
   
    public const int __ID__ = 2312771;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "en:" + En + ","
        + "zhCN:" + ZhCN + ","
        + "zhTW:" + ZhTW + ","
        + "}";
    }
}

}

