
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.StarForce
{
public partial class TbScene
{
    private readonly System.Collections.Generic.Dictionary<int, Scene> _dataMap;
    private readonly System.Collections.Generic.List<Scene> _dataList;
    
    public TbScene(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Scene>();
        _dataList = new System.Collections.Generic.List<Scene>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Scene _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Scene.DeserializeScene(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Scene> DataMap => _dataMap;
    public System.Collections.Generic.List<Scene> DataList => _dataList;

    public Scene GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Scene Get(int key) => _dataMap[key];
    public Scene this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

