
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.StarForce
{
public partial class TbUIForm
{
    private readonly System.Collections.Generic.Dictionary<int, UIForm> _dataMap;
    private readonly System.Collections.Generic.List<UIForm> _dataList;
    
    public TbUIForm(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UIForm>();
        _dataList = new System.Collections.Generic.List<UIForm>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            UIForm _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = UIForm.DeserializeUIForm(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UIForm> DataMap => _dataMap;
    public System.Collections.Generic.List<UIForm> DataList => _dataList;

    public UIForm GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UIForm Get(int key) => _dataMap[key];
    public UIForm this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

