
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.StarForce
{
public partial class TbMusic
{
    private readonly System.Collections.Generic.Dictionary<int, StarForce.Music> _dataMap;
    private readonly System.Collections.Generic.List<StarForce.Music> _dataList;
    
    public TbMusic(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StarForce.Music>();
        _dataList = new System.Collections.Generic.List<StarForce.Music>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            StarForce.Music _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = StarForce.Music.DeserializeMusic(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StarForce.Music> DataMap => _dataMap;
    public System.Collections.Generic.List<StarForce.Music> DataList => _dataList;

    public StarForce.Music GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StarForce.Music Get(int key) => _dataMap[key];
    public StarForce.Music this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

